version: '3.8'

services:

  # service2:
  #   image: samunderdocker/demo:latest
  #   ports:
  #    - 5002: 5002
  #   environment:
  #     - HDRNET_HOST=
  #     - HDRNET_PORT=8079

  # service3:
  #   image: samunderdocker/main_service:latest
  #   ports:
  #    - 8080: 8080
  #   environment:
  #     - HDRNET_HOST=
  #     - HDRNET_PORT=8079
      
  web:
    build: ./project
    ports:
      - 8004:8000
    command:  uvicorn main:app --host 0.0.0.0 --reload --ssl-keyfile /app/certs/key.pem --ssl-certfile /app/certs/cert.pem
    volumes:
      - ./project:/usr/src/app
      -  ./pk_certs:/app/certs 
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - SECRETKEY=9b52c64430979adc8d9523fa36f02fae28d18a5a537425c66af11016eb8e19a5
      - CLIENT_ACCESS_ID=ovvy-daas-api
      - CLIENT_ACCESS_KEY=ovvy-business-2024
      - DATABASE_HOST=35.225.223.91
      - DATABASE_NAME=users  # Update to your actual database name
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=test
      - DATABASE_PASSWORD=test
      - TOKEN_LIMIT=10080
      - TOKEN_ALGORITHM=HS256


    depends_on:
      - redis

  worker:
    build: ./project
    command: celery -A worker.celery worker --loglevel=info --logfile=logs/celery.log
    # volumes:
      # - ./project:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis

  redis:
    image: redis:7

  dashboard:
    build: ./project
    command: celery --broker=redis://redis:6379/0 flower  --port=5555 
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
      - worker
